main/MavenThought.PrDC.Demo/Models/TrackViewModel.cs
using System.Collections.Generic;
using MavenThought.PrDC.Api;

namespace MavenThought.PrDC.Demo.Models
{
    public class TrackViewModel
    {
        public ITrack Track { get; set; }

        public IEnumerable<IPresenterSession> Sessions { get; set; }
    }
}

main/MavenThought.PrDC.Demo/Controllers/AboutController.cs
using System.Web.Mvc;

namespace MavenThought.PrDC.Demo.Controllers
{
    public class AboutController : Controller
    {
        //
        // GET: /About/

        public ActionResult Index()
        {
            return View();
        }

    }
}

main/MavenThought.PrDC.Demo/Controllers/HomeController.cs
using System.Web.Mvc;

namespace MavenThought.PrDC.Demo.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

main/MavenThought.PrDC.Demo/Controllers/SessionsController.cs
using System.Web.Mvc;
using MavenThought.PrDC.Api;

namespace MavenThought.PrDC.Demo.Controllers
{
    /// <summary>
    /// Controller for sessions (i.e. speaker presentations)
    /// </summary>
    public class SessionsController : Controller
    {
        /// <summary>
        /// Repository to find the sessions
        /// </summary>
        private readonly IConference _conference;

        /// <summary>
        /// Initializes a new instance of the SessionsController class.
        /// </summary>
        /// <param name="conferenceRepo"></param>
        public SessionsController(IConference conferenceRepo)
        {
            this._conference = conferenceRepo;
        }

        //
        // GET: /Sessions/
        public ActionResult Index()
        {
            return View(this._conference.Sessions);
        }
    }
}

main/MavenThought.PrDC.Demo/Controllers/SpeakersController.cs
using System.Linq;
using System.Web.Mvc;
using MavenThought.PrDC.Api;

namespace MavenThought.PrDC.Demo.Controllers
{
    public class SpeakersController : Controller
    {
        /// <summary>
        /// Repository to use
        /// </summary>
        private readonly IConference conferenceRepo;

        /// <summary>
        /// Initializes a new instance of the SpeakersController class.
        /// </summary>
        /// <param name="conferenceRepo"></param>
        public SpeakersController(IConference conferenceRepo)
        {
            this.conferenceRepo = conferenceRepo;
        }

        //
        // GET: /Speakers/
        public ActionResult Index()
        {
            return View(conferenceRepo.Speakers.OrderBy(sp => sp.LastName));
        }
    }
}

main/MavenThought.PrDC.Demo/Controllers/TracksController.cs
using System.Web.Mvc;
using MavenThought.PrDC.Api;

namespace MavenThought.PrDC.Demo.Controllers
{
    public class TracksController : Controller
    {
        /// <summary>
        /// Repository to find the sessions
        /// </summary>
        private readonly IConference _conference;

        /// <summary>
        /// Initializes a new instance of the SessionsController class.
        /// </summary>
        /// <param name="conferenceRepo">Conference repository to use</param>
        public TracksController(IConference conferenceRepo)
        {
            this._conference = conferenceRepo;
        }
        
        //
        // GET: /Tracks/
        public ActionResult Index()
        {
            return View();
        }

        // Get: /Tracks/Detail
        public ActionResult Detail(string track)
        {
            return View();
        }
    }
}

main/MavenThought.PrDC.Demo/Views/About/Index.cshtml
@{
    ViewBag.Title = "About";
}

<h1>PrDc API Demo</h1>

<p>
    This demo illustrates the usage of the PrDC API.
</p>

<p>Feel free to contact me if u have any questions</p>

main/MavenThought.PrDC.Demo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h1>Welcome to PrDc API Demo!</h1>

main/MavenThought.PrDC.Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	    <title>Prairie Developer Conference API Demo</title>
	    <meta name="title" content="Prairie Developer Conference"/>		
	    <meta name="keywords" content=""/>
	    <meta name="description" content=""/>
	    <meta name="copyright" content="MavenThought Inc."/>
	    <meta name="revisit-after" content="15 days"/>
	    <meta name="robots" content="all"/>
	    <meta name="MSSmartTagsPreventParsing"" content="true"/>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    </head>

    <body>
        <div id="header">REST API Demo</div>
        <div id="menu">
          @Html.ActionLink("Presenters", "Index", "Speakers")
          @Html.ActionLink("Sessions", "Index", "Sessions")
          @Html.ActionLink("Tracks", "Index", "Tracks")
        </div>
        <div id="content">
            @RenderBody()
        </div>
    </body>
</html>

main/MavenThought.PrDC.Demo/Views/Speakers/Index.cshtml
@using MavenThought.PrDC.Demo.Helpers
@model IEnumerable<MavenThought.PrDC.Api.ISpeaker>
           
@{
    ViewBag.Title = "Speakers";
}

@foreach (var speaker in Model)
{
    <div class="element speaker">
        <div class="title">@speaker.FirstName @speaker.LastName</div>
        <div class="location">@speaker.Location</div>
        <div class="bio">@Html.Bio(speaker)</div>
        <div class="contact">@Html.MediaLinks(speaker)</div>
    </div>
}

main/MavenThought.PrDC.Demo/Views/Tracks/Detail.cshtml
@model IEnumerable<MavenThought.PrDC.Api.IPresenterSession>
           
@{
    ViewBag.Title = "Track Details";
}

<h2>Track @Model.First().Track</h2>

@foreach (var session in Model) { 	
    <div class="element session">
        <p class="title">@session.Title</p>
        <p>@session.Abstract</p>
        <p><b>Style:</b> @session.Style</p>			        
        <p><b>Speaker:</b> <i>@session.Presenter</i></p>
    </div>
}

main/MavenThought.PrDC.Demo/Views/Tracks/Index.cshtml
@model IEnumerable<MavenThought.PrDC.Api.ITrack>
           
@{
    ViewBag.Title = "Tracks";
}


<ul>
    @foreach (var vm in Model)
    {
        <li class="track">
            @vm.Name:
            @Html.ActionLink(@vm.NumberOfSessions.ToString(), "Detail", new { Track = @vm.Key })
        </li>
    }
</ul>